version: '3.9'
services:
  server: 
    build: ./server
    container_name: server_backend
    ports: 
      - '3000:3000'
  
  client: 
    build: ./client
    container_name: server_frontend
    network_mode: host
    depends_on:
      - server
  
  database:
    image: postgres:alpine3.19
    container_name: db
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=fotondb
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - foton-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - postgres

  apgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=bromankoya@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  foton-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge